name: myapp
description: App per messaggi vocali geolocalizzati
publish_to: none

version: 0.4.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - versioni verificate
  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.15.1
  firebase_messaging: ^14.7.1
  
  # Geolocalizzazione
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  
  # Audio
  flutter_sound: ^9.28.0
  
  # Notifiche - VERSIONI VERIFICATE
  flutter_local_notifications: ^17.2.3

  workmanager: ^0.6.0  # or check pub.dev for the newest version
  
  # Permessi
  permission_handler: ^11.0.1
  android_intent_plus: ^5.0.0
  
  # Storage
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  minio: ^3.1.0
  path: ^1.9.0
  uuid: ^4.5.1
  
  # UI
  cupertino_icons: ^1.0.7
  
  # Utilità
  url_launcher: ^6.3.0
  clipboard: ^2.0.2
  app_links: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/google_logo.png