name: myapp
description: App per messaggi vocali geolocalizzati
publish_to: none

version: 0.4.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # CONSIGLIO: rimuovi il pin esplicito di intl per evitare conflitti.
  # Se vuoi tenerlo, assicurati che sia compatibile con la tua versione di Flutter.
  # intl: ^0.20.2

  # Firebase - versioni verificate
  firebase_core: ^2.28.0
  firebase_auth: ^4.18.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.17.1
  firebase_messaging: ^14.7.1
  
  # Geolocalizzazione
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  
  # Audio
  flutter_sound: ^9.2.13
  
  # Notifiche
  flutter_local_notifications: ^17.2.3

  workmanager: ^0.6.0
  
  # Permessi
  permission_handler: ^11.0.1
  android_intent_plus: ^5.0.0
  
  # Storage
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  minio: ^3.1.0
  path: ^1.9.0
  uuid: ^4.5.1
  
  # UI
  cupertino_icons: ^1.0.7
  
  # Utilità
  url_launcher: ^6.3.0
  clipboard: ^2.0.2
  app_links: ^3.2.0

  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/google_logo.png
  generate: true   # <-- lascia solo questo (niente gen-l10n qui)
